import os
os.system("cls")

print(F"##############")
print(F" BENVENUTO/A!")
print(F"##############")
print("                         ")
print(" >> Come ti chiami?      ")
nome = input()
print("                         ")
print(" >> Da dove vieni?       ")
luogo = input()
print("                         ")
print(" >> In che anno sei nato?")
anno = int(input())
print("                         ")
print(" >> Che scuola frequenti?")
scuola = input()
print("                         ")
print("                         ")
età = 2024 - anno
print("########################################################################################")
print(F">> Tu hai {età} anni, frequenti la scuola {scuola}, ti chiami {nome} e vieni da {luogo}")
print("########################################################################################")